name: Build and Push to Harbor

on:
  push:
    branches:
      - main

jobs:
  docker:

    runs-on: self-hosted

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login \
            ${{ secrets.HARBOR_REGISTRY }} \
            -u "${{ secrets.HARBOR_USERNAME }}" \
            --password-stdin

      - name: Build Image
        run: |
          docker build \
            -t ${{ secrets.HARBOR_REGISTRY }}/demo01/hi-cicd-demo:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push \
            ${{ secrets.HARBOR_REGISTRY }}/demo01/hi-cicd-demo:${{ github.sha }}

      - name: Show Image
        run: |
          docker images
